const Jobs = {
  live: {
    1: {
      id: 1,
      title: "Web Developer",
      company: "LineupX",
      location: "location",
      skill: ["Html", "Css", "React"],
      experience: "0-1 years",
      type: "Full Time",
      no_candidates: 5,
      salary: "25-30 lakh",
    },
    2: {
      id: 2,
      title: "DevOps",
      company: "LineupX",
      location: "location",
      skill: ["Html", "Css", "React"],
      experience: "0-1 years",
      type: "Full Time",
      no_candidates: 5,
      salary: "25-30 lakh",
    },

    3: {
      id: 3,
      title: "Full Stack ",
      company: "LineupX",
      location: "location",
      skill: ["Html", "Css", "React"],
      experience: "0-1 years",
      type: "Full Time",
      no_candidates: 5,
      salary: "25-30 lakh",
    },
    4: {
      id: 4,
      title: "Machine learning",
      company: "LineupX",
      location: "location",
      skill: ["Html", "Css", "React", "Redux", "Node", "Html"],
      experience: "0-1 years",
      type: "Full Time",
      no_candidates: 5,
      salary: "25-30 lakh",
    },
    5: {
      id: 5,
      title: "Backend Developer",
      company: "LineupX",
      location: "location",
      skill: ["Html", "Css", "React", "Redux", "Node", "Html"],
      experience: "0-1 years",
      type: "Full Time",
      no_candidates: 5,
      salary: "25-30 lakh",
    },
  },
  accepted: {
    6: {
      id: 6,
      title: "Full Stack",
      company: "LineupX",
      location: "location",
      skill: ["Html", "Css", "React", "Redux", "Node", "Html"],
      experience: "0-1 years",
      type: "Full Time",
      no_candidates: 5,
      salary: "25-30 lakh",
    },
  },
  rejected: {},
};

export default Jobs;
